<div id="pie"> <pre><A href="/a/b/normas/dedicatorias.html" >Dedicatorias</A>   <A href="/a/b/normas/normas.html" >Ayuda y Normas de Uso</A>       <A href="/sugerencias.php" >Sugerencias</A></pre></div>
<div id="pie2"> &copy;2008-<script type="text/javascript"> var fecha=new Date(); var ano=fecha.getFullYear(); document.write(ano); </script> Pablo Lleó Garcia todos los derechos reservados 
</div>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-8645230-1");
pageTracker._trackPageview();
} catch(err) {}</script>

</body>
</html>
